version: "3"

services:
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"

  celery:
    build: .
    command: celery -A config worker -l info
    ports:
      - "8001:8001"
    depends_on:
      - "rabbitmq"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py createsuperuser  --noinput && gunicorn config.wsgi -b 0.0.0.0:8000"
    container_name: the_eye
    volumes:
      - .:/theeye
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "celery"
